// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/browse" | "/browse/[id]" | "/dashboard" | "/edit/[[...id]]" | "/embed/[id]" | "/new/[[...id]]" | "/offline" | "/posts/[[...id]]" | "/privacy" | "/series/[id]" | "/series/[id]/edit" | "/user/[id]" | "/view/[id]"
type AppRouteHandlerRoutes = "/api/ai/credentials" | "/api/ai/credentials/[provider]" | "/api/attachments/[filename]" | "/api/attachments/[filename]/content" | "/api/auth/[...nextauth]" | "/api/blob" | "/api/blob/[hash]" | "/api/blob/link" | "/api/completion" | "/api/copilot" | "/api/copilot/threads" | "/api/copilot/threads/[id]" | "/api/documents" | "/api/documents/[id]" | "/api/documents/[id]/agent/accept" | "/api/documents/[id]/agent/discard" | "/api/documents/[id]/attachments" | "/api/documents/[id]/backlinks" | "/api/documents/[id]/children" | "/api/documents/[id]/move" | "/api/documents/[id]/proposals" | "/api/documents/[id]/proposals/[revisionId]/approve" | "/api/documents/[id]/proposals/[revisionId]/reject" | "/api/documents/[id]/status" | "/api/documents/agent" | "/api/documents/changes" | "/api/documents/check" | "/api/documents/new/[id]" | "/api/documents/update-times" | "/api/docx/[id]" | "/api/embed" | "/api/events" | "/api/export" | "/api/health" | "/api/import" | "/api/mcp" | "/api/notes" | "/api/notes/[id]" | "/api/notes/[id]/bring-to-front" | "/api/notes/canvas" | "/api/notes/canvas/[id]" | "/api/og" | "/api/projects" | "/api/projects/[id]" | "/api/projects/[id]/move" | "/api/proposals" | "/api/proposals/count" | "/api/revalidate" | "/api/revisions" | "/api/revisions/[id]" | "/api/series" | "/api/series/[id]" | "/api/series/[id]/move" | "/api/series/[id]/posts" | "/api/series/available-posts" | "/api/thumbnails/[id]" | "/api/usage" | "/api/users/[id]" | "/api/users/check" | "/docx/[id]" | "/pdf/[id]"
type PageRoutes = never
type LayoutRoutes = "/" | "/edit"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/ai/credentials": {}
  "/api/ai/credentials/[provider]": { "provider": string; }
  "/api/attachments/[filename]": { "filename": string; }
  "/api/attachments/[filename]/content": { "filename": string; }
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/blob": {}
  "/api/blob/[hash]": { "hash": string; }
  "/api/blob/link": {}
  "/api/completion": {}
  "/api/copilot": {}
  "/api/copilot/threads": {}
  "/api/copilot/threads/[id]": { "id": string; }
  "/api/documents": {}
  "/api/documents/[id]": { "id": string; }
  "/api/documents/[id]/agent/accept": { "id": string; }
  "/api/documents/[id]/agent/discard": { "id": string; }
  "/api/documents/[id]/attachments": { "id": string; }
  "/api/documents/[id]/backlinks": { "id": string; }
  "/api/documents/[id]/children": { "id": string; }
  "/api/documents/[id]/move": { "id": string; }
  "/api/documents/[id]/proposals": { "id": string; }
  "/api/documents/[id]/proposals/[revisionId]/approve": { "id": string; "revisionId": string; }
  "/api/documents/[id]/proposals/[revisionId]/reject": { "id": string; "revisionId": string; }
  "/api/documents/[id]/status": { "id": string; }
  "/api/documents/agent": {}
  "/api/documents/changes": {}
  "/api/documents/check": {}
  "/api/documents/new/[id]": { "id": string; }
  "/api/documents/update-times": {}
  "/api/docx/[id]": { "id": string; }
  "/api/embed": {}
  "/api/events": {}
  "/api/export": {}
  "/api/health": {}
  "/api/import": {}
  "/api/mcp": {}
  "/api/notes": {}
  "/api/notes/[id]": { "id": string; }
  "/api/notes/[id]/bring-to-front": { "id": string; }
  "/api/notes/canvas": {}
  "/api/notes/canvas/[id]": { "id": string; }
  "/api/og": {}
  "/api/projects": {}
  "/api/projects/[id]": { "id": string; }
  "/api/projects/[id]/move": { "id": string; }
  "/api/proposals": {}
  "/api/proposals/count": {}
  "/api/revalidate": {}
  "/api/revisions": {}
  "/api/revisions/[id]": { "id": string; }
  "/api/series": {}
  "/api/series/[id]": { "id": string; }
  "/api/series/[id]/move": { "id": string; }
  "/api/series/[id]/posts": { "id": string; }
  "/api/series/available-posts": {}
  "/api/thumbnails/[id]": { "id": string; }
  "/api/usage": {}
  "/api/users/[id]": { "id": string; }
  "/api/users/check": {}
  "/browse": {}
  "/browse/[id]": { "id": string; }
  "/dashboard": {}
  "/docx/[id]": { "id": string; }
  "/edit": {}
  "/edit/[[...id]]": { "id"?: string[]; }
  "/embed/[id]": { "id": string; }
  "/new/[[...id]]": { "id"?: string[]; }
  "/offline": {}
  "/pdf/[id]": { "id": string; }
  "/posts/[[...id]]": { "id"?: string[]; }
  "/privacy": {}
  "/series/[id]": { "id": string; }
  "/series/[id]/edit": { "id": string; }
  "/user/[id]": { "id": string; }
  "/view/[id]": { "id": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/edit": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
