// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(public)/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/user/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/user/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/view/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/view/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/view/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(workspace)/browse/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/browse/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(workspace)/browse/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(workspace)/browse/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/browse">> = Specific
  const handler = {} as typeof import("../../src/app/(workspace)/browse/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(workspace)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(workspace)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(workspace)/edit/[[...id]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/edit/[[...id]]">> = Specific
  const handler = {} as typeof import("../../src/app/(workspace)/edit/[[...id]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(workspace)/new/[[...id]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/new/[[...id]]">> = Specific
  const handler = {} as typeof import("../../src/app/(workspace)/new/[[...id]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(workspace)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(workspace)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(workspace)/posts/[[...id]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/posts/[[...id]]">> = Specific
  const handler = {} as typeof import("../../src/app/(workspace)/posts/[[...id]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(workspace)/series/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/series/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/(workspace)/series/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(workspace)/series/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/series/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(workspace)/series/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/embed/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/embed/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/embed/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/offline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/offline">> = Specific
  const handler = {} as typeof import("../../src/app/offline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/credentials/[provider]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/credentials/[provider]">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/credentials/[provider]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/credentials/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/credentials">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/credentials/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/attachments/[filename]/content/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attachments/[filename]/content">> = Specific
  const handler = {} as typeof import("../../src/app/api/attachments/[filename]/content/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/attachments/[filename]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attachments/[filename]">> = Specific
  const handler = {} as typeof import("../../src/app/api/attachments/[filename]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/blob/[hash]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blob/[hash]">> = Specific
  const handler = {} as typeof import("../../src/app/api/blob/[hash]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/blob/link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blob/link">> = Specific
  const handler = {} as typeof import("../../src/app/api/blob/link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/blob/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blob">> = Specific
  const handler = {} as typeof import("../../src/app/api/blob/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/completion/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/completion">> = Specific
  const handler = {} as typeof import("../../src/app/api/completion/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/copilot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/copilot">> = Specific
  const handler = {} as typeof import("../../src/app/api/copilot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/copilot/threads/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/copilot/threads/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/copilot/threads/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/copilot/threads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/copilot/threads">> = Specific
  const handler = {} as typeof import("../../src/app/api/copilot/threads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/documents/[id]/agent/accept/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents/[id]/agent/accept">> = Specific
  const handler = {} as typeof import("../../src/app/api/documents/[id]/agent/accept/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/documents/[id]/agent/discard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents/[id]/agent/discard">> = Specific
  const handler = {} as typeof import("../../src/app/api/documents/[id]/agent/discard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/documents/[id]/attachments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents/[id]/attachments">> = Specific
  const handler = {} as typeof import("../../src/app/api/documents/[id]/attachments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/documents/[id]/backlinks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents/[id]/backlinks">> = Specific
  const handler = {} as typeof import("../../src/app/api/documents/[id]/backlinks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/documents/[id]/children/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents/[id]/children">> = Specific
  const handler = {} as typeof import("../../src/app/api/documents/[id]/children/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/documents/[id]/move/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents/[id]/move">> = Specific
  const handler = {} as typeof import("../../src/app/api/documents/[id]/move/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/documents/[id]/proposals/[revisionId]/approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents/[id]/proposals/[revisionId]/approve">> = Specific
  const handler = {} as typeof import("../../src/app/api/documents/[id]/proposals/[revisionId]/approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/documents/[id]/proposals/[revisionId]/reject/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents/[id]/proposals/[revisionId]/reject">> = Specific
  const handler = {} as typeof import("../../src/app/api/documents/[id]/proposals/[revisionId]/reject/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/documents/[id]/proposals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents/[id]/proposals">> = Specific
  const handler = {} as typeof import("../../src/app/api/documents/[id]/proposals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/documents/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/documents/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/documents/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents/[id]/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/documents/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/documents/agent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents/agent">> = Specific
  const handler = {} as typeof import("../../src/app/api/documents/agent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/documents/changes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents/changes">> = Specific
  const handler = {} as typeof import("../../src/app/api/documents/changes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/documents/check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents/check">> = Specific
  const handler = {} as typeof import("../../src/app/api/documents/check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/documents/new/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents/new/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/documents/new/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/documents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents">> = Specific
  const handler = {} as typeof import("../../src/app/api/documents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/documents/update-times/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents/update-times">> = Specific
  const handler = {} as typeof import("../../src/app/api/documents/update-times/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/docx/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/docx/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/docx/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/embed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/embed">> = Specific
  const handler = {} as typeof import("../../src/app/api/embed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/export">> = Specific
  const handler = {} as typeof import("../../src/app/api/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/import">> = Specific
  const handler = {} as typeof import("../../src/app/api/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mcp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp">> = Specific
  const handler = {} as typeof import("../../src/app/api/mcp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notes/[id]/bring-to-front/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notes/[id]/bring-to-front">> = Specific
  const handler = {} as typeof import("../../src/app/api/notes/[id]/bring-to-front/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notes/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notes/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/notes/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notes/canvas/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notes/canvas/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/notes/canvas/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notes/canvas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notes/canvas">> = Specific
  const handler = {} as typeof import("../../src/app/api/notes/canvas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notes">> = Specific
  const handler = {} as typeof import("../../src/app/api/notes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/og/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/og">> = Specific
  const handler = {} as typeof import("../../src/app/api/og/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[id]/move/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/move">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[id]/move/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/proposals/count/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/proposals/count">> = Specific
  const handler = {} as typeof import("../../src/app/api/proposals/count/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/proposals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/proposals">> = Specific
  const handler = {} as typeof import("../../src/app/api/proposals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/revalidate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/revalidate">> = Specific
  const handler = {} as typeof import("../../src/app/api/revalidate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/revisions/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/revisions/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/revisions/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/revisions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/revisions">> = Specific
  const handler = {} as typeof import("../../src/app/api/revisions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/series/[id]/move/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/series/[id]/move">> = Specific
  const handler = {} as typeof import("../../src/app/api/series/[id]/move/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/series/[id]/posts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/series/[id]/posts">> = Specific
  const handler = {} as typeof import("../../src/app/api/series/[id]/posts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/series/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/series/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/series/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/series/available-posts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/series/available-posts">> = Specific
  const handler = {} as typeof import("../../src/app/api/series/available-posts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/series/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/series">> = Specific
  const handler = {} as typeof import("../../src/app/api/series/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/thumbnails/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/thumbnails/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/thumbnails/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/usage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/usage">> = Specific
  const handler = {} as typeof import("../../src/app/api/usage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/check">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/docx/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/docx/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/docx/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pdf/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/pdf/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/pdf/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(public)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(workspace)/edit/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/edit">> = Specific
  const handler = {} as typeof import("../../src/app/(workspace)/edit/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(workspace)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(workspace)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
